# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - main
#    trigger when publish to the branch other than main and release
#      - '*'
#      - '!main'
#      - '!release*'


jobs:
  prepare:
    name: Prepare Environment
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout the code
        uses: actions/checkout@v2 # user other action, The uses parameter follow this syntax {owner}/{repo}@{ref}.
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

  test:
    name: Run Unit test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Unit tests
        run: ./gradlew test

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Assemble App APK
        run: ./gradlew assembleDebug
      - name: Upload App APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Assemble Android Instrumented Unit Test
        run: ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  firebase: