name: Minor Release
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 0 * * 1'

jobs:
  MinorRelease:
    name: Minor release from main branch
    runs-on: ubuntu-latest
    steps:
      ## Prepare ##
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      ## Release ##
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Extract secrets
        run: |
          echo "${{ secrets.RELEASE_SECRETS }}" > secrets.tar.asc
          gpg -d --passphrase "${{ secrets.RELEASE_SECRETS_PASSPHRASE }}" --batch secrets.tar.asc > secrets.tar
          tar xvf secrets.tar
      - name: Increase Minor version tag, Create RC branch and Release
        run: ./gradlew MinorRelease
      - name: Cleanup
        run: rm -rf secrets.tar keystore.jks keystore.properties google-api-service.json
        if: ${{ always() }}