name: Minor Release
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 0 * * 1'

jobs:
  MinorRelease:
    name: Minor release from main branch
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare-cicd
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Extract secrets
        run: |
          echo "${{ secrets.RELEASE_SECRETS }}" > secrets.tar.asc
          gpg -d --passphrase "${{ secrets.RELEASE_SECRETS_PASSPHRASE }}" --batch secrets.tar.asc > secrets.tar
          tar xvf secrets.tar
      - name: Minior Release
        description: Increase Minor version tag, Create RC branch and Release
        run: ./gradlew MinorRelease
      - name: Cleanup
        run: rm -rf secrets.tar keystore.jks keystore.properties google-api-service.json
        if: ${{ always() }}