name: Patch Release
on:
  workflow_dispatch:

jobs:
  PatchRelease:
    name: Bump Patch Version on RC branch and Release
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare-cicd
      - name: Extract secrets
        run: |
          echo "${{ secrets.RELEASE_SECRETS }}" > secrets.tar.asc
          gpg -d --passphrase "${{ secrets.RELEASE_SECRETS_PASSPHRASE }}" --batch secrets.tar.asc > secrets.tar
          tar xvf secrets.tar
      - name: Patch Release
        description: Increase Patch version tag and Release
        run: ./gradlew PatchRelease
      - name: Cleanup
        uses: rm -rf secrets.tar keystore.jks keystore.properties google-api-service.json
        if: ${{ always() }}