name: Verification
on:
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
    branches:
      - main


jobs:
  jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      ## Prepare ##
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-

      ## Verification ##
      - name: Tests
        run: ./gradlew testDebugUnitTest

      ## Report ##
      - name: Print Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      ### TODO: Collect and Upload TestReport as artifact
#      - name: Collect all test results from all modules
#        if: always()
#        run: ./scripts/aggregate-test-reports.sh build/test-reports
#
#      - name: Archive test results
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: reports
#          path: build/test-results

  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 31 ]
    steps:
      ## Prepare ##
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-

      ## Verification ##
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-x86_64-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          arch: x86_64
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest --stacktrace

# Do it after we have screenshot/acceptance test in other jobs
#      - name: Archive Test APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: tests-apk
#          path: app/build/outputs/apk/androidTest/debug
